apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${app_name}
  namespace: ${argo_namespace}
spec:
  project: default
  source:
    repoURL: ${repo_url}
    targetRevision: ${chart_revision}
    path: ${path}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        ${replace(indent(8, values_file), "%", "%%")}
  destination:
    server: ${destination_server}
    namespace: ${app_namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
