global:
  domain: "$(hostname)"

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: $(ingress_class_name)
    annotations:
      cert-manager.io/cluster-issuer: $(cert_manager_issuer_name)
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true