global:
  domain: "${argo_hostname}"

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    # controller: generic
    ingressClassName: "${ingress_class}"
    annotations:
      cert-manager.io/cluster-issuer: "${cluster_issuer}"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true
