apiVersion: v1
kind: Secret
metadata:
  name: wordpress-repo
  namespace: ${namespace}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: ${url}/wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: ${url}/mariadb
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: helm
  url: ${url}
  password: ${password}
  username: ${username}
