# Description
#
# Exfiltration consists of techniques that adversaries may use to steal data
# from your network. Once they’ve collected data, adversaries often package it
# to avoid detection while removing it. This can include compression and encryption.
# Techniques for getting data out of a target network typically include
# transferring it over their command and control channel or an alternate channel
# and may also include putting size limits on the transmission.

# Attack Scenario
#
# It's important to note that file copy tools can be leveraged by attackers for
# exfiltrating sensitive data and transferring malicious payloads into the workloads.
# Additionally, it can also assist in lateral movement within the system.
# It's crucial to take proactive measures to prevent these attacks from occurring.
# Attack Type Credential Access, Lateral movements, Information Disclosure
# Actual Attack DarkBeam Data Breach, Shields Health Care Group data breach





apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-wordpress-remote-file-copy
  namespace: ${app_namespace}
spec:
  action: Block
  message: Alert! remote file copy tools execution prevented.
  process:
    matchPaths:
    - path: /usr/bin/rsync
    - path: /bin/rsync
    - path: /usr/bin/scp
    - path: /bin/scp
    - path: /usr/bin/scp
    - path: /bin/scp
  selector:
    matchLabels: {}
  severity: 5
  tags:
  - MITRE
  - MITRE_TA0008_lateral_movement
  - MITRE_TA0010_exfiltration
  - MITRE_TA0006_credential_access
  - MITRE_T1552_unsecured_credentials
  - NIST_800-53_SI-4(18)
  - NIST
  - NIST_800-53
  - NIST_800-53_SC-4
